# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a29288e13d3c8214358ddb1dec693caa242e432fc7ea2484c7bf077ddc6b64b22074091ba4249015ca0ce43ba2386e070a87ac4927ad57044000aa84ed672425

test:
  secret_key_base: 73295be4a766330e21c6583fd0a065e81dd7478595963e0e9803cfe8e67ac9387762e479f57fb85bd89251f1f6afa8d772e7de3aa52ae5955fdf2558510e4a13

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
